language: node_js

node_js:
  - "12"

install:
  - curl -L https://deno.land/x/install/install.sh | sh -s v1.2.1
  - export PATH="$HOME/.deno/bin:$PATH"
  - deno --version

script:
  - deno lint --unstable .
  - deno test .
