language: node_js

variables:
  DENO_VERSION: "v0.11.0"

install:
  - curl -L https://deno.land/x/install/install.sh | sh -s $(DENO_VERSION)
  - export PATH="$HOME/.deno/bin:$PATH"

script:
  - ./test.ts
